theme: minima


---
layout: post
title: "My First Blog"
date: 2025-01-06
---

Welcome to my first blog post!

collections:
  showcase:
    output: true

nav:
  - title: Papers
    url: /statistics/2025-01-05-Papers.md



